cesko-digital/blog

.gitignore, package.json, yarn.lock
Viz commit logy. Pokud existuje nějaké lepší řešení (JavaScript nehraju :–), klidně můžeme zařídit jinak.
=> Drobná oprava buildu

src/components/news-card/styles.js, src/components/post-card/index.js, src/components/post-card/styles.js, src/components/post/styles.js, src/templates/post/index.css
=> Vylepšení stylů odkazů

data/site-config.js, gatsby-config.js, package.json, src/components/layout/head.js, src/components/layout/index.jsx, src/components/seo/index.jsx, yarn.lock
=> Implementace analytics

content/news.yaml
=> Chybné řazení aktualit

content/posts/2019/2019-10-01-zaznam-setkani.md
=> Add an article with the meetup video recordings

src/components/layout/footer.js, src/components/layout/styles.js
Přidání jednoduché věty. Vycházel jsem z tohoto [webu](https://phpfashion.com/jak-na-souhlas-s-cookie-v-eu). Nejsem právník, ale myslím, že takto je to dostačující. 
Poslušně prosím o review a případný merge.
=> Přidání informace o používání cookies

gatsby-config.js
Fixes #32 
Omlouvám se za prodlevu.
=> Přidání perexu do textu článku v RSS

src/components/news-card/index.js, src/components/news-card/styles.js, src/pages/index.jsx, src/templates/post/index.jsx
- removed underline
- extended clickable area
- maximum of 3 items
- removed styled-components clutter
Picture is worth a thousand words: https://i.imgur.com/2KxLPc5.jpg
(GitHub: This fixes #27.)
=> Modified rendering of news-card

content/posts/2019/2019-10-22-novinky.md
@Horm, máš prosím představu, proč nám něco žere název kanálu `#general` v prvním odstavci? (Zkoušel jsem odrazit jako `\#general`, ale pak se to zase objeví včetně toho lomítka.)
=> Přehled novinek za září

content/posts/2019/2019-10-01-zaznam-setkani.md, content/posts/2019/2019-11-7-rozhovor-vereha.md, content/posts/2019/2019-11-7-vereha-interview.md, src/components/post/lang-versions.js
=> Rozhovor s Olivií Verehou

gatsby-config.js
=> Odstranění EN článků z RSS

CONTRIBUTING.md
Fixes #46 
Vytvořil jsem první verzi. Anglická gramatika není moje nejsilnější stránka, takže předpokládám, že nějaká úprava bude nutná. 
@zoul, je to zatím bez popisu ohledně čisté historie. Rád bych využil nabídky provést někde úklid společně při callu.
=> Přidání popisu "How To Contribute"

README.md, content/posts/2019/2019-11-13-nove-posily.md, gatsby-node.js, src/helpers/graph.js, src/helpers/node.js, src/pages/index.jsx
=> Přidání podpory "featured" článků

README.md
=> Přidání informací ohledně obrázků do README

content/posts/2020/2020-3-10-hlidac-insolvenci.md
Zatím pouze náhled, ještě ladíme. @HormCodes, tady v závěru v sekci _Lidé_ bysme chtěli upíchnout ty medailonky – odladit je asi můžem někde jinde, tohle je čistě pro představu.
=> Blog post o dokončeném projektu Hlídač insolvencí

jsconfig.json, src/components/layout/index.css, src/components/news-card/helpers.js, src/components/post-card/helpers.js, src/components/post-card/styles.js, src/components/post/b16-tomorrow-dark.css
Je to tak ve většině souborů - někde to lítalo náhodně.
Je v tom i #80, tak jestli s #80 bude problém, můžu ten commit tady revertnout.
=> Refactoring: úprava odřádkování na konzistentní - 2 mezery na tab

.prettierrc, package.json, src/components/layout/footer.js, src/components/layout/header.js, src/components/layout/media-queries.js, src/components/layout/styles.js, src/components/post-listing/index.jsx, src/components/post-listing/styles.js, src/templates/post/index.jsx, yarn.lock
Fix #82 
CSS nená úplně můj šálek kávy. Bylo by toho tam více na přepracování, ale nemá smysl to řešit, když se plánuje rework.
=> Náhrada react-grid-system screen class selektory

gatsby-config.js
=> Remove press releases from blog RSS

content/posts/2020/2020-7-10-novinky.md, src/components/post/index.js
Přidán obsah, @zoul můžeš pak příští týden nahrát obrázek na data.cesko.digital?
=> Newsletter za červen

gatsby-node.js, src/components/layout/head.js, src/components/post-listing/index.jsx, src/components/post-listing/styles.js, src/components/post/index.js, src/components/press-card/index.js, src/components/seo/index.jsx, src/pages/index.jsx, src/templates/post/index.jsx
Přidání podpory pro absolutní importy pro `src` složku + vytvoření aliasu pro `data` složku -> `@data/site-config`.
Tvar aliasu je otevřený diskuzi. Issue #92.
=> Podpora absolutních importů

content/press/2020-9-17-ucime-online.md
Před mergnutím je potřeba přidat náhledový obrázek.
=> Nová tisková zpráva Učíme online

content/authors.yaml, content/press/2020-11-09-informacni-web-cr.md
=> Adding press release - informacni web cr spusten

content/authors.yaml, content/press/2020-11-02-skoleni-pedagogu.md
Hotové až na chybějící cover obrázek.
=> Add press release - ucimeonline.cz

content/press/2020-11-04-zpravodajsky-storytelling.md
Hotové až na chybějící cover obrázek.
=> Adding press release - zpravodajsky storytelling

content/authors.yaml, content/posts/2020/2020-11-25-interview-habl.md, content/posts/2020/2020-11-25-nedluzim-statu.md, content/posts/2020/2020-11-25-rozhovor-nedluzim-statu.md
Všechno by mělo být hotové, čekáme jen na závěrečný souhlas s publikací.
=> Obsah ke spuštění Nedlužím státu

content/authors.yaml, content/posts/2021/2021-3-22-rok-ucime-online.md, content/posts/2021/2021-3-23-rok-ucime-online.md
=> Narozeniny Učíme online: intro článek

src/components/layout/index.jsx
Sundal jsem odkaz na neexistující anglickou mutaci a změnil cíl odkazu Co děláme. Aspoň něco™ :)
=> Opravy základních navigačních kiksů po nasazení nového webu

gatsby-node.js, static/admin/config.yml, static/admin/index.html
* [Dokumentace k Netlify CMS](https://www.netlifycms.org/docs/)
* [Nasazená verze](https://blog-git-netlify-cms-ceskodigital.vercel.app/admin/#/)
=> Integrace Netlify CMS

api/articles.ts, package.json, yarn.lock
Tohle je podpora pro https://github.com/cesko-digital/web/issues/445 a další případy, kdy potřebujeme strojově čitelný index článků.
=> API pro přehled článků

content/press/2021-12-7-zacni-ucit.md, lib/post-loading.ts, lib/post.test.ts, lib/site-data.ts, lib/utils.ts
Původně nám nevalidní články rozbily celý build, teď je prostě zalogujeme a přeskočíme. Vracím taky do hry tiskovku, která to původně způsobila.
=> Přeskakování nevalidních článků

global.css
Fixes https://github.com/cesko-digital/blog/issues/243
=> Use Fira Sans for article body text

public/admin/index.html
Nasazeno tady:
📌 https://blog-git-topic-decap-ceskodigital.vercel.app/
=> Upgrade Netlify CMS na Decap
